-- MySQL Script generated by MySQL Workbench
-- Thu Dec 15 23:40:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `nombre` VARCHAR(16) NOT NULL,
  `apellido` VARCHAR(255) NULL,
  `foto` LONGTEXT NOT NULL,
  `nacimiento` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `email` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`estudios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudios` (
  `id` INT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `titulo` VARCHAR(45) NULL,
  `institucion` VARCHAR(45) NULL,
  `fecha_inicio` LONGTEXT NULL,
  `fecha_fin` LONGTEXT NULL,
  `Usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Usuario_id`),
  INDEX `fk_estudios_Usuario_idx` (`Usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_estudios_Usuario`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proyectos` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `descripcion` LONGTEXT NOT NULL,
  `foto` LONGTEXT NULL DEFAULT CURRENT_TIMESTAMP,
  `proyectoscol` VARCHAR(45) NULL,
  `Usuario_id` INT NOT NULL,
  PRIMARY KEY (`Usuario_id`),
  CONSTRAINT `fk_proyectos_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '		';


-- -----------------------------------------------------
-- Table `mydb`.`trabajos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trabajos` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `descripcion` TEXT NOT NULL,
  `puesto` TEXT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_inicio` LONGTEXT NULL,
  `fecha_fin` LONGTEXT NULL,
  `trabajoscol` VARCHAR(45) NULL,
  `Usuario_id` INT NOT NULL,
  PRIMARY KEY (`Usuario_id`),
  CONSTRAINT `fk_trabajos_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
